debug: false
db:
  host: "127.0.0.1"
  port: 3306
  dbName: "maxblog-be-template"
  userName: "root"
  password: "123456"

redis:
  host: "127.0.0.1"
  port: 6379

consul:
  host: "127.0.0.1"
  port: 8500

server:
  srvName: "maxblog-be-template"
  host: "127.0.0.1"
  port: 9095
  tags:
    - maxblog-be-template
    - maxblog
